Edit resource image
inclusion-numerique/la-base pull request #33
Opened 2023-05-25 13:28 UTC by hugues-m

2023-05-25 16:05 UTC, desoindx requested changes

2023-05-25 16:05 UTC, desoindx commented on apps/web/cypress/e2e/resource/resourceEdition.cy.ts
> +      it.only("Acceptation 3 - Edition de l'image", () => {
Remove only
we should have a lint rule for this :)

2023-05-25 16:05 UTC, desoindx commented on apps/web/src/components/Resource/Edition/EditableImage.module.css
> +    border: 1px dashed var(--border-default-grey);
```suggestion
    border: var(--slim-grey-border);
```

2023-05-25 16:05 UTC, desoindx commented on apps/web/src/components/ResponsiveUploadedImage.tsx
> +/* eslint react/jsx-props-no-spreading: off */
Why here ? better close to the issue no ?

2023-05-25 16:05 UTC, desoindx commented on apps/web/src/server/resources/feature/EditImage.server.ts
> +    ...rest,
On lit pas une image a sa ressource ? ca pourrait etre cool pour delete ?

2023-05-25 16:05 UTC, desoindx commented on packages/ui/src/components/Form/FileFormField.tsx
> +      }) => {
a changer dans la stack ?

2023-05-29 13:20 UTC, hugues-m commented on apps/web/src/server/resources/feature/EditImage.server.ts
> +    ...rest,
A re-checker quand on aura des images de profil / base / resource , avec une version publiée et une en brouillon, si il y a du undo / redo, pour savoir ce qu'on peut supprimer ou non.
Je suis pas au clair sur ce qu'on voudra pouvoir faire

2023-05-29 17:39 UTC, Clrk approved these changes

2023-06-05 13:15 UTC, merged