Feat/update collection
inclusion-numerique/la-base pull request #97
Opened 2023-12-07 15:27 UTC by marc-gavanier

2023-12-08 09:01 UTC, hugues-m commented on apps/web/src/app/dsfr-overrides.css
> +    border-bottom: 1px solid var(--border-default-grey);
Pour info, on a `border-bottom: var(--slim-grey-border)`

2023-12-08 09:02 UTC, hugues-m commented on apps/web/src/app/dsfr-overrides.css
> +  color: var(--text-inverted-error);
👍

2023-12-08 09:03 UTC, hugues-m commented on apps/web/src/components/AttributePreview.tsx
> +export const AttributePreview = ({
On a un composant `LabelAndValue`, est-ce qu'il ferait l'affaire à la place de celui là ?

2023-12-13 07:57 UTC, hugues-m commented on apps/web/src/components/EditableCard.tsx
> +  children: ReactElement[]
A re-confirmer ensemble, mais ici, je préfèrerai utiliser les props pour les children plutôt que children.find dans le render.
```ts
preview: ReactNode,
editing: ReactNode,
```

J'aime bien la version actuelle à la lecture à l'utilisation car cela ressemble plus à du html bien structuré, mais la version en props est plus typesafe (on est obligé d'avoir un mode preview et editing pour une EditableCard), et  consistante avec @codegouvfr/react-dsfr , react-select, react-hook-form ou les children sont passés dans des names props ou customisés avec des render props.

Qu'est ce que tu en penses?

2023-12-14 13:58 UTC, marc-gavanier commented on apps/web/src/components/Collection/Edition/CollectionInformationsEdition.tsx
> +    <EditableCardForm
Utilisation de `EditableCardForm`

2023-12-14 13:59 UTC, marc-gavanier commented on apps/web/src/components/Collection/Edition/CollectionInformationsEdition.tsx
> +    setCollection({ ...collection, ...data })
La mise à jour de l'état permet d'éviter de passer par le routeur : celà élimine le cas où la sauvegarde ne mets pas à jour la vue

2023-12-14 14:09 UTC, marc-gavanier commented on apps/web/src/ui/LabelAndValue.tsx
> +    <Component className={className}>
Tout ça fonctionne bien, mais ça met quand même beaucoup de responsabilité sur ce composant, dis-moi si tu préfères que j'en fasse deux (à minima inline et block)

2023-12-14 14:36 UTC, hugues-m requested changes

2023-12-14 14:36 UTC, hugues-m commented on apps/web/src/components/Collection/Edition/CollectionInformationsEdition.tsx
> +    setCollection({ ...collection, ...data })
Cela fonctionne pour la page d'édition mais ca ne sera pas suffisant pour la page collection ou la carte collection dans la liste des collections.

e.g. -> 
Je vois ma liste de collections
Je vais sur la page de ma collection
Je clique sur éditer
Je change le titre
Je retourne sur la page de ma collection, le titre n'est pas changé
Je retourne sur la liste de mes collections, le titre n'est pas changé

Le router.refresh() permet d'invalider ces path de liste et de page

2023-12-14 14:36 UTC, hugues-m commented on apps/web/src/components/EditableCardForm.tsx
> +  const [isLoading, setLoadingState] = useState(false)
Pas besoin de ce useState() 

`const isLoading = form.formState.isSubmitting || form.formState.isSubmitSuccessful`

2023-12-14 14:36 UTC, hugues-m commented on apps/web/src/ui/LabelAndValue.tsx
> +    <Component className={className}>
Je suis pas certain, je pense c'est ok pour cette PR et on pourra en rediscuter en remontant ca dans stack ?

2023-12-14 14:48 UTC, marc-gavanier commented on apps/web/src/components/Collection/Edition/CollectionInformationsEdition.tsx
> +    setCollection({ ...collection, ...data })
Effectivement, je n'avais pas remarqué le souci à la navigation. Ça fonctionne parfaitement avec `router.refresh()` :)

2023-12-14 14:49 UTC, marc-gavanier commented on apps/web/src/components/EditableCardForm.tsx
> +  const [isLoading, setLoadingState] = useState(false)
Je ne vois pas trop là, je veux bien en discuter de vive voix

2023-12-14 17:07 UTC, hugues-m approved these changes

2023-12-22 12:28 UTC, hugues-m approved these changes

2023-12-22 17:50 UTC, marc-gavanier commented on packages/e2e/cypress/e2e/base/baseDeletion.cy.ts
> +    cy.appUrlShouldBe(`/profils/${user.id}/bases`)
Proposition pour rediriger l'utilisateur sur la liste des bases plutôt que la page d'accueil après une suppression (j'ai mis en place le même comportement pour les collections)

2024-01-04 13:19 UTC, merged